### ISSUE TITLE
Image fails to load @ 1.1.0

### ISSUE THREAD

**Issue by asartz** [pqina/filepond-plugin-file-poster#2]
Hi there,
after latest update image fails to load. the image displays ok when using previous version 1.0.0. 
![screenshot 2018-10-24 at 16 03 42](https://user-images.githubusercontent.com/4661961/47432448-d0a7c900-d7a6-11e8-9c4a-bd9e76d95532.png)
Image is stored in a public s3 bucket with cors enabled.
just wanted to let you know.
Thank you for your efforts.

**Comment by rikschennink** [comment]
Oh, yeah, didn't consider this, it's reading out pixel data to determine the average image color for a future layout update. But yes, if images are fetched from a remote URL that's not allowed due to CORS. If it's not a problem you can set CORS headers on the bucket and it should work. I'll see if I can come up with a solution.

**Comment by asartz** [comment]
Sorry, i wasn't clear before. By saying cors enabled i actually meant that 

    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedHeader>*</AllowedHeader>

**Comment by rikschennink** [comment]
I've just updated the file-poster plugin, should now work again.

**Comment by kezek** [comment]
Hey , I'm still having this issue. I'm on the latest stables.

**Comment by rikschennink** [comment]
@kezek Do you still get the error when all plugins are disabled? Can you pinpoint the problem to the file-poster plugin?

**Comment by kezek** [comment]
Ok , did some steps to provide some hopefully useful repro steps:

Plugins used:
- filepond-plugin-file-poster
- filepond-plugin-image-preview
- filepond-plugin-file-validate-type

Injected in that order.

I managed to get rid of the error with filepond-plugin-file-poster v1.0.0 (thanks to @asartz for specifying that v1.0 doesn't have this issue).

So basically with v1.1.1 I get the CORS error , with v1.0.0 I do not. Hopefully I provided some insight. 

Implementation is cookie cutter , did nothing hacky/ fancy

I do not get the error without filepond-plugin-file-poster plugin since it's not fetching the file without it.

**Comment by rikschennink** [comment]
@kezek Just published version `1.1.2` of the file poster plugin and version `3.1.2` of the image preview plugin should fix the issue.

**Comment by kezek** [comment]
Amazing ! Updated and no issues at all.

Thanks a lot and keep up the excellent work ! Really appreciate it

**Comment by kezek** [comment]
Scratch that , false alarm , got too excited but I actually forgot to rebuild.

Unfortunately the problem is still there with 1.1.2 , the only way to get rid of the issue is keeping the poster plugin at 1.0.0.

**Comment by rikschennink** [comment]
I can't reproduce this locally:

```js
FilePond.create(el, {
    files: [
        {
            source:1234,
            options: {
                type: 'local',
                file: {
                    name: 'my-file.png',
                    size: 1234,
                    type: 'image/png'
                },
                metadata:{
                    poster: 'https://i.imgur.com/hRliFiT.jpg'
                }
            }
        }
    ]
});
```

The imgur URL response headers:

![screenshot 2018-10-31 at 07 58 43](https://user-images.githubusercontent.com/1132575/47771284-eeaf8500-dce2-11e8-8b74-0ea3bab474d3.png)

Can you compare to your response headers and see if you missed something. 

I also wonder if the problem is the same in every browser.

A publicly accessible test case would be helpful.

**Comment by kezek** [comment]
There you go

![screenshot from 2018-10-31 03-52-23](https://user-images.githubusercontent.com/790391/47772066-28d25400-dcee-11e8-9e78-ea9914de3ce0.png)

I'll try to create a test case but I'm really short on time currently , stand by

**Comment by rikschennink** [comment]
@kezek I just tested this is in Firefox and Chrome but they correctly load the image.

![screenshot 2018-10-31 at 08 26 50](https://user-images.githubusercontent.com/1132575/47772361-bca02200-dce6-11e8-89a1-9863839a9136.png)

Maybe it's a cache problem?

**Comment by kezek** [comment]
I'm not sure what's going on. 

All I know now is that with 1.0.0 => no issue. With 1.1.1 I get the CORS issue. Sorry , can't provide more info for now

**Comment by chung-nguyen** [comment]
In my case, it is because of this line:
`img.crossOrigin = 'Anonymous';`

I cloned poster plugin source code, remove that line and it works fine for me.

My suggestion: leave crossOrigin property as an option.

**Comment by rikschennink** [comment]
@chung-nguyen Just published version 2.1.0 that adds this feature
https://github.com/pqina/filepond-plugin-file-poster/releases/tag/2.1.0

**Comment by kezek** [comment]
Sorry for necroing this , but for anyone else dealing with this issue here is a good rundown of the whole situation: https://serverfault.com/questions/856904/chrome-s3-cloudfront-no-access-control-allow-origin-header-on-initial-xhr-req/856948#856948

Haven't been able to fix it as of yet , and upgrading this library to the latest stable didn't do it for me.

Not saying this is the library's fault , the issue is quite complex.
